---
title: "Self-exciting_negative_binomial_distribution_process_and_critical_properties_of_intensity_distribution"
subtitle: "Critical_properties_of_intensity_distribution"
author: "K.Sakuraba"
date: "2023/5/14"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#0
# RData

```{r}
library(data.table)
data <- fread("Data/1/001/09/NBD001.csv")
hist <- hist(data$Intensity,breaks=c(0,(max(data$Intensity)**(1/50))**(0:50)))
x<-hist$mids ; y<- hist$density
hist1 <- data.frame(x,y)
save(hist1, file = "Data/1/001/09/NBD001.rda")
```

# 1
##K=1
### $\nu_0 = 0.01,n=0.9,0.99,0.999$

```{r}
rm(list=ls())
library(data.table)

#omega=0.01#############################################################################################
load("Data/1/001/09/NBD001.rda")
load("Data/1/001/099/NBD001.rda")
load("Data/1/001/0999/NBD001.rda")

gamma_nu0_tau_omega<-function(nu0,tau,omega) 1-2*nu0*tau/(omega+1)
gamma <- gamma_nu0_tau_omega(0.01,1,0.01) 

t1  <- "exponent=0.9802"
t2  <- expression(n=0.9)
t3  <- expression(n=0.99)
t4  <- expression(n=0.999)
plot(hist3$x,hist3$y,log="xy",
     xlab=expression(nu),
     ylab=expression(paste("P"[SS],"(",nu,")")),
     main=expression(paste("(a) ",omega,"=0.01,",nu[0],"=0.01")),
     ylim=c(1e-8,1e-1),col=1,pch=16,cex.lab=1.05)
points(hist2$x,hist2$y,col=1,pch=1)
points(hist1$x,hist1$y,col=1,pch=20)
curve(0.02*x**(-gamma),add=TRUE,col=1,lwd=3)
legend("bottomleft",legend=c(t1,t4,t3,t2),lty=c(1,-1,-1,-1),lwd=2,col=c(1,1,1,1),pch=c(-1,16,1,20),cex=1.0 )

#omega=1.0###################################################################################################
rm(list=ls())
load("Data/1/1/09/NBD001.rda")
load("Data/1/1/099/NBD001.rda")
load("Data/1/1/0999/NBD001.rda")

gamma_nu0_tau_omega<-function(nu0,tau,omega) 1-2*nu0*tau/(omega+1)
gamma <- gamma_nu0_tau_omega(0.01,1,1) 

t1  <- "exponent=0.99"
t2  <- expression(n=0.9)
t3  <- expression(n=0.99)
t4  <- expression(n=0.999)
plot(hist3$x,hist3$y,log="xy",
     xlab=expression(nu),
     ylab=expression(paste("P"[SS],"(",nu,")")),
     main=expression(paste("(b) ",omega,"=1.0,",nu[0],"=0.01")),
     ylim=c(1e-9,1e-1),col=1,pch=16,cex.lab=1.05)
points(hist2$x,hist2$y,col=1,pch=1)
points(hist1$x,hist1$y,col=1,pch=20)
curve(0.01*x**(-gamma),add=TRUE,col=1,lwd=3)
legend("bottomleft",legend=c(t1,t4,t3,t2),lty=c(1,-1,-1,-1),lwd=2,col=c(1,1,1,1),pch=c(-1,16,1,20),cex=1.0 )

#omega=10.0##################################################################################################
rm(list=ls())
load("Data/1/10/09/NBD001.rda")
load("Data/1/10/099/NBD001.rda")
load("Data/1/10/0999/NBD001.rda")

gamma_nu0_tau_omega<-function(nu0,tau,omega) 1-2*nu0*tau/(omega+1)
gamma <- gamma_nu0_tau_omega(0.01,1,10) 

t1  <- "exponent=0.9982"
t2  <- expression(n=0.9)
t3  <- expression(n=0.99)
t4  <- expression(n=0.999)
plot(hist3$x,hist3$y,log="xy",
     xlab=expression(nu),
     ylab=expression(paste("P"[SS],"(",nu,")")),
     main=expression(paste("(c) ",omega,"=10.0,",nu[0],"=0.01")),
     ylim=c(1e-9,1e-2),col=1,pch=16,cex.lab=1.05)
points(hist2$x,hist2$y,col=1,pch=1)
points(hist1$x,hist1$y,col=1,pch=20)
curve(0.002*x**(-gamma),add=TRUE,col=1,lwd=3)
legend("bottomleft",legend=c(t1,t4,t3,t2),lty=c(1,-1,-1,-1),lwd=2,col=c(1,1,1,1),pch=c(-1,16,1,20),cex=1.0 )
```

### $\nu_0 = 0.2,n=0.9,0.99,0.999$

```{r}
rm(list=ls())
library(data.table)

#omega=0.01#############################################################################################
load("Data/1/001/09/NBD02.rda")
load("Data/1/001/099/NBD02.rda")
load("Data/1/001/0999/NBD02.rda")

gamma_nu0_tau_omega<-function(nu0,tau,omega) 1-2*nu0*tau/(omega+1)
gamma <- gamma_nu0_tau_omega(0.2,1,0.01)  

t1  <- "exponent=0.604"
t2  <- expression(n=0.9)
t3  <- expression(n=0.99)
t4  <- expression(n=0.999)
plot(hist3$x,hist3$y,log="xy",
     xlab=expression(nu),
     ylab=expression(paste("P"[SS],"(",nu,")")),
     main=expression(paste("(d) ",omega,"=0.01,",nu[0],"=0.2")),
     ylim=c(1e-8,1e0),col=1,pch=16,cex.lab=1.05)
points(hist2$x,hist2$y,col=1,pch=1)
points(hist1$x,hist1$y,col=1,pch=20)
curve(0.05*x**(-gamma),add=TRUE,col=1,lwd=3)
legend("bottomleft",legend=c(t1,t4,t3,t2),lty=c(1,-1,-1,-1),lwd=2,col=c(1,1,1,1),pch=c(-1,16,1,20),cex=1.0 )

#omega=1.0###################################################################################################
rm(list=ls())
load("Data/1/1/09/NBD02.rda")
load("Data/1/1/099/NBD02.rda")
load("Data/1/1/0999/NBD02.rda")

gamma_nu0_tau_omega<-function(nu0,tau,omega) 1-2*nu0*tau/(omega+1)
gamma <- gamma_nu0_tau_omega(0.2,1,1)  

t1  <- "exponent=0.8"
t2  <- expression(n=0.9)
t3  <- expression(n=0.99)
t4  <- expression(n=0.999)
plot(hist3$x,hist3$y,log="xy",
     xlab=expression(nu),
     ylab=expression(paste("P"[SS],"(",nu,")")),
     main=expression(paste("(e) ",omega,"=1.0,",nu[0],"=0.2")),
     ylim=c(1e-8,1e0),col=1,pch=16,cex.lab=1.05)
points(hist2$x,hist2$y,col=1,pch=1)
points(hist1$x,hist1$y,col=1,pch=20)
curve(0.07*x**(-gamma),add=TRUE,col=1,lwd=3)
legend("bottomleft",legend=c(t1,t4,t3,t2),lty=c(1,-1,-1,-1),lwd=2,col=c(1,1,1,1),pch=c(-1,16,1,20),cex=1.0 )

#omega=10.0##################################################################################################
rm(list=ls())
load("Data/1/10/09/NBD02.rda")
load("Data/1/10/099/NBD02.rda")
load("Data/1/10/0999/NBD02.rda")

gamma_nu0_tau_omega<-function(nu0,tau,omega) 1-2*nu0*tau/(omega+1)
gamma <- gamma_nu0_tau_omega(0.2,1,10)  

t1  <- "exponent=0.9636"
t2  <- expression(n=0.9)
t3  <- expression(n=0.99)
t4  <- expression(n=0.999)
plot(hist3$x,hist3$y,log="xy",
     xlab=expression(nu),
     ylab=expression(paste("P"[SS],"(",nu,")")),
     main=expression(paste("(f) ",omega,"=10.0,",nu[0],"=0.2")),
     ylim=c(1e-8,1e0),col=1,pch=16,cex.lab=1.05)
points(hist2$x,hist2$y,col=1,pch=1)
points(hist1$x,hist1$y,col=1,pch=20)
curve(0.04*x**(-gamma),add=TRUE,col=1,lwd=3)
legend("bottomleft",legend=c(t1,t4,t3,t2),lty=c(1,-1,-1,-1),lwd=2,col=c(1,1,1,1),pch=c(-1,16,1,20),cex=1.0 )
```

### $\nu_0 = 1.0,n=0.9,0.99,0.999$

```{r}
rm(list=ls())
library(data.table)

#omega=0.01#############################################################################################
load("Data/1/001/09/NBD1.rda")
load("Data/1/001/099/NBD1.rda")
load("Data/1/001/0999/NBD1.rda")

gamma_nu0_tau_omega<-function(nu0,tau,omega) 1-2*nu0*tau/(omega+1)
gamma <- gamma_nu0_tau_omega(1,1,0.01)  

t1  <- "exponent=-0.9802"
t2  <- expression(n=0.9)
t3  <- expression(n=0.99)
t4  <- expression(n=0.999)
plot(hist3$x,hist3$y,log="xy",
     xlab=expression(nu),
     ylab=expression(paste("P"[SS],"(",nu,")")),
     main=expression(paste("(g) ",omega,"=0.01,",nu[0],"=1.0")),
     ylim=c(1e-8,1e0),col=1,pch=16,cex.lab=1.05)
points(hist2$x,hist2$y,col=1,pch=1)
points(hist1$x,hist1$y,col=1,pch=20)
curve(0.000004*x**(-gamma),add=TRUE,col=1,lwd=3)
curve(0.0004*x**(-gamma),add=TRUE,col=1,lwd=3)
legend("bottomleft",legend=c(t1,t4,t3,t2),lty=c(1,-1,-1,-1),lwd=2,col=c(1,1,1,1),pch=c(-1,16,1,20),cex=1.0 )

#omega=1.0###################################################################################################
rm(list=ls())
load("Data/1/1/09/NBD1.rda")
load("Data/1/1/099/NBD1.rda")
load("Data/1/1/0999/NBD1.rda")

gamma_nu0_tau_omega<-function(nu0,tau,omega) 1-2*nu0*tau/(omega+1)
gamma <- gamma_nu0_tau_omega(1,1,1)  

t1  <- "exponent=0.0"
t2  <- expression(n=0.9)
t3  <- expression(n=0.99)
t4  <- expression(n=0.999)
plot(hist3$x,hist3$y,log="xy",
     xlab=expression(nu),
     ylab=expression(paste("P"[SS],"(",nu,")")),
     main=expression(paste("(h) ",omega,"=1.0,",nu[0],"=1.0")),
     ylim=c(1e-8,1e0),col=1,pch=16,cex.lab=1.05)
points(hist2$x,hist2$y,col=1,pch=1)
points(hist1$x,hist1$y,col=1,pch=20)
curve(0.001*x**(-gamma),add=TRUE,col=1,lwd=3)
curve(0.01*x**(-gamma),add=TRUE,col=1,lwd=3)
legend("bottomleft",legend=c(t1,t4,t3,t2),lty=c(1,-1,-1,-1),lwd=2,col=c(1,1,1,1),pch=c(-1,16,1,20),cex=1.0 )

#omega=10.0##################################################################################################
rm(list=ls())
load("Data/1/10/09/NBD1.rda")
load("Data/1/10/099/NBD1.rda")
load("Data/1/10/0999/NBD1.rda")

gamma_nu0_tau_omega<-function(nu0,tau,omega) 1-2*nu0*tau/(omega+1)
gamma <- gamma_nu0_tau_omega(1,1,10)  

t1  <- "exponent=0.8182"
t2  <- expression(n=0.9)
t3  <- expression(n=0.99)
t4  <- expression(n=0.999)
plot(hist3$x,hist3$y,log="xy",
     xlab=expression(nu),
     ylab=expression(paste("P"[SS],"(",nu,")")),
     main=expression(paste("(i) ",omega,"=10.0,",nu[0],"=1.0")),
     ylim=c(1e-9,1e0),col=1,pch=16,cex.lab=1.05)
points(hist2$x,hist2$y,col=1,pch=1)
points(hist1$x,hist1$y,col=1,pch=20)
curve(0.05*x**(-gamma),add=TRUE,col=1,lwd=3)
legend("bottomleft",legend=c(t1,t4,t3,t2),lty=c(1,-1,-1,-1),lwd=2,col=c(1,1,1,1),pch=c(-1,16,1,20),cex=1.0 )
```

##K=2
### $\nu_0 = 0.01,n=0.9,0.99,0.999$

```{r}
rm(list=ls())
library(data.table)

#omega=0.01#############################################################################################
load("Data/2/001/09/NBD001.rda")
load("Data/2/001/099/NBD001.rda")
load("Data/2/001/0999/NBD001.rda")

gamma_nu0_tau_omega<-function(nu0,tau1,tau2,n1,n2,omega) 1-2*nu0*(tau1*n1+tau2*n2)/(omega+1)
gamma <- gamma_nu0_tau_omega(0.01,1,3,0.5,0.5,0.01)

t1  <- "exponent=0.9604"
t2  <- expression(n=0.9)
t3  <- expression(n=0.99)
t4  <- expression(n=0.999)
plot(hist3$x,hist3$y,log="xy",
     xlab=expression(nu),
     ylab=expression(paste("P"[SS],"(",nu,")")),
     main=expression(paste("(a) ",omega,"=0.01,",nu[0],"=0.01")),
     ylim=c(1e-8,1e0),col=1,pch=16,cex.lab=1.05)
points(hist2$x,hist2$y,col=1,pch=1)
points(hist1$x,hist1$y,col=1,pch=20)
curve(0.03*x**(-gamma),add=TRUE,col=1,lwd=3)
legend("bottomleft",legend=c(t1,t4,t3,t2),lty=c(1,-1,-1,-1),lwd=2,col=c(1,1,1,1),pch=c(-1,16,1,20),cex=1.0 )

#omega=1.0###################################################################################################
rm(list=ls())
load("Data/2/1/09/NBD001.rda")
load("Data/2/1/099/NBD001.rda")
load("Data/2/1/0999/NBD001.rda")

gamma_nu0_tau_omega<-function(nu0,tau1,tau2,n1,n2,omega) 1-2*nu0*(tau1*n1+tau2*n2)/(omega+1)
gamma <- gamma_nu0_tau_omega(0.01,1,3,0.5,0.5,1)

t1  <- "exponent=0.98"
t2  <- expression(n=0.9)
t3  <- expression(n=0.99)
t4  <- expression(n=0.999)
plot(hist3$x,hist3$y,log="xy",
     xlab=expression(nu),
     ylab=expression(paste("P"[SS],"(",nu,")")),
     main=expression(paste("(b) ",omega,"=1.0,",nu[0],"=0.01")),
     ylim=c(1e-8,1e0),col=1,pch=16,cex.lab=1.05)
points(hist2$x,hist2$y,col=1,pch=1)
points(hist1$x,hist1$y,col=1,pch=20)
curve(0.02*x**(-gamma),add=TRUE,col=1,lwd=3)
legend("bottomleft",legend=c(t1,t4,t3,t2),lty=c(1,-1,-1,-1),lwd=2,col=c(1,1,1,1),pch=c(-1,16,1,20),cex=1.0 )

#omega=10.0##################################################################################################
rm(list=ls())
load("Data/2/10/09/NBD001.rda")
load("Data/2/10/099/NBD001.rda")
load("Data/2/10/0999/NBD001.rda")

gamma_nu0_tau_omega<-function(nu0,tau1,tau2,n1,n2,omega) 1-2*nu0*(tau1*n1+tau2*n2)/(omega+1)
gamma <- gamma_nu0_tau_omega(0.01,1,3,0.5,0.5,10)

t1  <- "exponent=0.9964"
t2  <- expression(n=0.9)
t3  <- expression(n=0.99)
t4  <- expression(n=0.999)
plot(hist3$x,hist3$y,log="xy",
     xlab=expression(nu),
     ylab=expression(paste("P"[SS],"(",nu,")")),
     main=expression(paste("(c) ",omega,"=10.0,",nu[0],"=0.01")),
     ylim=c(1e-9,1e0),col=1,pch=16,cex.lab=1.05)
points(hist2$x,hist2$y,col=1,pch=1)
points(hist1$x,hist1$y,col=1,pch=20)
curve(0.004*x**(-gamma),add=TRUE,col=1,lwd=3)
legend("bottomleft",legend=c(t1,t4,t3,t2),lty=c(1,-1,-1,-1),lwd=2,col=c(1,1,1,1),pch=c(-1,16,1,20),cex=1.0 )
```

### $\nu_0 = 0.2,n=0.9,0.99,0.999$

```{r}
rm(list=ls())
library(data.table)

#omega=0.01#############################################################################################
load("Data/2/001/09/NBD02.rda")
load("Data/2/001/099/NBD02.rda")
load("Data/2/001/0999/NBD02.rda")

gamma_nu0_tau_omega<-function(nu0,tau1,tau2,n1,n2,omega) 1-2*nu0*(tau1*n1+tau2*n2)/(omega+1)
gamma <- gamma_nu0_tau_omega(0.2,1,3,0.5,0.5,0.01)

t1  <- "exponent=0.2079"
t2  <- expression(n=0.9)
t3  <- expression(n=0.99)
t4  <- expression(n=0.999)
plot(hist3$x,hist3$y,log="xy",
     xlab=expression(nu),
     ylab=expression(paste("P"[SS],"(",nu,")")),
     main=expression(paste("(d) ",omega,"=0.01,",nu[0],"=0.2")),
     ylim=c(1e-7,1e0),col=1,pch=16,cex.lab=1.05)
points(hist2$x,hist2$y,col=1,pch=1)
points(hist1$x,hist1$y,col=1,pch=20)
curve(0.01*x**(-gamma),add=TRUE,col=1,lwd=3)
#curve(0.07*x**(-gamma),add=TRUE,col=1,lwd=3)
legend("bottomleft",legend=c(t1,t4,t3,t2),lty=c(1,-1,-1,-1),lwd=2,col=c(1,1,1,1),pch=c(-1,16,1,20),cex=1.0 )

#omega=1.0###################################################################################################
rm(list=ls())
load("Data/2/1/09/NBD02.rda")
load("Data/2/1/099/NBD02.rda")
load("Data/2/1/0999/NBD02.rda")

gamma_nu0_tau_omega<-function(nu0,tau1,tau2,n1,n2,omega) 1-2*nu0*(tau1*n1+tau2*n2)/(omega+1)
gamma <- gamma_nu0_tau_omega(0.2,1,3,0.5,0.5,1)

t1  <- "exponent=0.6"
t2  <- expression(n=0.9)
t3  <- expression(n=0.99)
t4  <- expression(n=0.999)
plot(hist3$x,hist3$y,log="xy",
     xlab=expression(nu),
     ylab=expression(paste("P"[SS],"(",nu,")")),
     main=expression(paste("(e) ",omega,"=1.0,",nu[0],"=0.2")),
     ylim=c(1e-8,1e0),col=1,pch=16,cex.lab=1.05)
points(hist2$x,hist2$y,col=1,pch=1)
points(hist1$x,hist1$y,col=1,pch=20)
curve(0.05*x**(-gamma),add=TRUE,col=1,lwd=3)
#curve(0.1*x**(-gamma),add=TRUE,col=1,lwd=3)
legend("bottomleft",legend=c(t1,t4,t3,t2),lty=c(1,-1,-1,-1),lwd=2,col=c(1,1,1,1),pch=c(-1,16,1,20),cex=1.0 )

#omega=10.0##################################################################################################
rm(list=ls())
load("Data/2/10/09/NBD02.rda")
load("Data/2/10/099/NBD02.rda")
load("Data/2/10/0999/NBD02.rda")

gamma_nu0_tau_omega<-function(nu0,tau1,tau2,n1,n2,omega) 1-2*nu0*(tau1*n1+tau2*n2)/(omega+1)
gamma <- gamma_nu0_tau_omega(0.2,1,3,0.5,0.5,10)

t1  <- "exponent=0.9273"
t2  <- expression(n=0.9)
t3  <- expression(n=0.99)
t4  <- expression(n=0.999)
plot(hist3$x,hist3$y,log="xy",
     xlab=expression(nu),
     ylab=expression(paste("P"[SS],"(",nu,")")),
     main=expression(paste("(f) ",omega,"=10.0,",nu[0],"=0.2")),
     ylim=c(1e-8,1e0),col=1,pch=16,cex.lab=1.05)
points(hist2$x,hist2$y,col=1,pch=1)
points(hist1$x,hist1$y,col=1,pch=20)
curve(0.06*x**(-gamma),add=TRUE,col=1,lwd=3)
legend("bottomleft",legend=c(t1,t4,t3,t2),lty=c(1,-1,-1,-1),lwd=2,col=c(1,1,1,1),pch=c(-1,16,1,20),cex=1.0 )
```

### $\nu_0 = 1.0,n=0.9,0.99,0.999$

```{r}
rm(list=ls())
library(data.table)

#omega=0.01#############################################################################################
load("Data/2/001/09/NBD1.rda")
load("Data/2/001/099/NBD1.rda")
load("Data/2/001/0999/NBD1.rda")

gamma_nu0_tau_omega<-function(nu0,tau1,tau2,n1,n2,omega) 1-2*nu0*(tau1*n1+tau2*n2)/(omega+1)
gamma <- gamma_nu0_tau_omega(1,1,3,0.5,0.5,0.01)

t1  <- "exponent=-2.9604"
t2  <- expression(n=0.9)
t3  <- expression(n=0.99)
t4  <- expression(n=0.999)
plot(hist3$x,hist3$y,log="xy",
     xlab=expression(nu),
     ylab=expression(paste("P"[SS],"(",nu,")")),
     main=expression(paste("(g) ",omega,"=0.01,",nu[0],"=1.0")),
     ylim=c(1e-8,1e0),col=1,pch=16,cex.lab=1.05)
points(hist2$x,hist2$y,col=1,pch=1)
points(hist1$x,hist1$y,col=1,pch=20)
curve(0.0000005*x**(-gamma),add=TRUE,col=1,lwd=3)
curve(0.00000000005*x**(-gamma),add=TRUE,col=1,lwd=3)
#curve(0.0000004*x**(-gamma),add=TRUE,col=1,lwd=3)
legend("bottomleft",legend=c(t1,t4,t3,t2),lty=c(1,-1,-1,-1),lwd=2,col=c(1,1,1,1),pch=c(-1,16,1,20),cex=1.0 )

#omega=1.0###################################################################################################
rm(list=ls())
load("Data/2/1/09/NBD1.rda")
load("Data/2/1/099/NBD1.rda")
load("Data/2/1/0999/NBD1.rda")

gamma_nu0_tau_omega<-function(nu0,tau1,tau2,n1,n2,omega) 1-2*nu0*(tau1*n1+tau2*n2)/(omega+1)
gamma <- gamma_nu0_tau_omega(1,1,3,0.5,0.5,1)

t1  <- "exponent=-1.0"
t2  <- expression(n=0.9)
t3  <- expression(n=0.99)
t4  <- expression(n=0.999)
plot(hist3$x,hist3$y,log="xy",
     xlab=expression(nu),
     ylab=expression(paste("P"[SS],"(",nu,")")),
     main=expression(paste("(h) ",omega,"=1.0,",nu[0],"=1.0")),
     ylim=c(1e-8,1e0),col=1,pch=16,cex.lab=1.05)
points(hist2$x,hist2$y,col=1,pch=1)
points(hist1$x,hist1$y,col=1,pch=20)
curve(0.0005*x**(-gamma),add=TRUE,col=1,lwd=3)
curve(0.000005*x**(-gamma),add=TRUE,col=1,lwd=3)
legend("bottomleft",legend=c(t1,t4,t3,t2),lty=c(1,-1,-1,-1),lwd=2,col=c(1,1,1,1),pch=c(-1,16,1,20),cex=1.0 )

#omega=10.0##################################################################################################
rm(list=ls())
load("Data/2/10/09/NBD1.rda")
load("Data/2/10/099/NBD1.rda")
load("Data/2/10/0999/NBD1.rda")

gamma_nu0_tau_omega<-function(nu0,tau1,tau2,n1,n2,omega) 1-2*nu0*(tau1*n1+tau2*n2)/(omega+1)
gamma <- gamma_nu0_tau_omega(1,1,3,0.5,0.5,10)

t1  <- "exponent=0.6364"
t2  <- expression(n=0.9)
t3  <- expression(n=0.99)
t4  <- expression(n=0.999)
plot(hist3$x,hist3$y,log="xy",
     xlab=expression(nu),
     ylab=expression(paste("P"[SS],"(",nu,")")),
     main=expression(paste("(i) ",omega,"=10.0,",nu[0],"=1.0")),
     ylim=c(1e-8,1e0),col=1,pch=16,cex.lab=1.05)
points(hist2$x,hist2$y,col=1,pch=1)
points(hist1$x,hist1$y,col=1,pch=20)
curve(0.03*x**(-gamma),add=TRUE,col=1,lwd=3)
legend("bottomleft",legend=c(t1,t4,t3,t2),lty=c(1,-1,-1,-1),lwd=2,col=c(1,1,1,1),pch=c(-1,16,1,20),cex=1.0 )
```

##K=3
### $\nu_0 = 0.01,n=0.9,0.99,0.999$

```{r}
rm(list=ls())
library(data.table)

#omega=0.01#############################################################################################
load("Data/3/001/09/NBD001.rda")
load("Data/3/001/099/NBD001.rda")
load("Data/3/001/0999/NBD001.rda")

gamma_nu0_tau_omega<-function(nu0,tau1,tau2,tau3,n1,n2,n3,omega) 1-2*nu0*(tau1*n1+tau2*n2+tau3*n3)/(omega+1)
gamma <- gamma_nu0_tau_omega(0.01,1,2,3,0.3,0.2,0.5,0.01) 

t1  <- "exponent=0.9564"
t2  <- expression(n=0.9)
t3  <- expression(n=0.99)
t4  <- expression(n=0.999)
plot(hist3$x,hist3$y,log="xy",
     xlab=expression(nu),
     ylab=expression(paste("P"[SS],"(",nu,")")),
     main=expression(paste("(a) ",omega,"=0.01,",nu[0],"=0.01")),
     ylim=c(1e-8,1e0),col=1,pch=16,cex.lab=1.05)
points(hist2$x,hist2$y,col=1,pch=1)
points(hist1$x,hist1$y,col=1,pch=20)
curve(0.04*x**(-gamma),add=TRUE,col=1,lwd=3)
legend("bottomleft",legend=c(t1,t4,t3,t2),lty=c(1,-1,-1,-1),lwd=2,col=c(1,1,1,1),pch=c(-1,16,1,20),cex=1.0 )

#omega=1.0###################################################################################################
rm(list=ls())
load("Data/3/1/09/NBD001.rda")
load("Data/3/1/099/NBD001.rda")
load("Data/3/1/0999/NBD001.rda")

gamma_nu0_tau_omega<-function(nu0,tau1,tau2,tau3,n1,n2,n3,omega) 1-2*nu0*(tau1*n1+tau2*n2+tau3*n3)/(omega+1)
gamma <- gamma_nu0_tau_omega(0.01,1,2,3,0.3,0.2,0.5,1) 

t1  <- "exponent=0.978"
t2  <- expression(n=0.9)
t3  <- expression(n=0.99)
t4  <- expression(n=0.999)
plot(hist3$x,hist3$y,log="xy",
     xlab=expression(nu),
     ylab=expression(paste("P"[SS],"(",nu,")")),
     main=expression(paste("(b) ",omega,"=1.0,",nu[0],"=0.01")),
     ylim=c(1e-8,1e0),col=1,pch=16,cex.lab=1.05)
points(hist2$x,hist2$y,col=1,pch=1)
points(hist1$x,hist1$y,col=1,pch=20)
curve(0.02*x**(-gamma),add=TRUE,col=1,lwd=3)
legend("bottomleft",legend=c(t1,t4,t3,t2),lty=c(1,-1,-1,-1),lwd=2,col=c(1,1,1,1),pch=c(-1,16,1,20),cex=1.0 )

#omega=10.0##################################################################################################
rm(list=ls())
load("Data/3/10/09/NBD001.rda")
load("Data/3/10/099/NBD001.rda")
load("Data/3/10/0999/NBD001.rda")

gamma_nu0_tau_omega<-function(nu0,tau1,tau2,tau3,n1,n2,n3,omega) 1-2*nu0*(tau1*n1+tau2*n2+tau3*n3)/(omega+1)
gamma <- gamma_nu0_tau_omega(0.01,1,2,3,0.3,0.2,0.5,10) 

t1  <- "exponent=0.996"
t2  <- expression(n=0.9)
t3  <- expression(n=0.99)
t4  <- expression(n=0.999)
plot(hist3$x,hist3$y,log="xy",
     xlab=expression(nu),
     ylab=expression(paste("P"[SS],"(",nu,")")),
     main=expression(paste("(c) ",omega,"=10.0,",nu[0],"=0.01")),
     ylim=c(1e-9,1e0),col=1,pch=16,cex.lab=1.05)
points(hist2$x,hist2$y,col=1,pch=1)
points(hist1$x,hist1$y,col=1,pch=20)
curve(0.005*x**(-gamma),add=TRUE,col=1,lwd=3)
legend("bottomleft",legend=c(t1,t4,t3,t2),lty=c(1,-1,-1,-1),lwd=2,col=c(1,1,1,1),pch=c(-1,16,1,20),cex=1.0 )
```

### $\nu_0 = 0.2,n=0.9,0.99,0.999$

```{r}
rm(list=ls())
library(data.table)

#omega=0.01#############################################################################################
load("Data/3/001/09/NBD02.rda")
load("Data/3/001/099/NBD02.rda")
load("Data/3/001/0999/NBD02.rda")

gamma_nu0_tau_omega<-function(nu0,tau1,tau2,tau3,n1,n2,n3,omega) 1-2*nu0*(tau1*n1+tau2*n2+tau3*n3)/(omega+1)
gamma <- gamma_nu0_tau_omega(0.2,1,2,3,0.3,0.2,0.5,0.01) 

t1  <- "exponent=0.9564"
t2  <- expression(n=0.9)
t3  <- expression(n=0.99)
t4  <- expression(n=0.999)
plot(hist3$x,hist3$y,log="xy",
     xlab=expression(nu),
     ylab=expression(paste("P"[SS],"(",nu,")")),
     main=expression(paste("(d) ",omega,"=0.01,",nu[0],"=0.2")),
     ylim=c(1e-8,1e0),col=1,pch=16,cex.lab=1.05)
points(hist2$x,hist2$y,col=1,pch=1)
points(hist1$x,hist1$y,col=1,pch=20)
curve(0.008*x**(-gamma),add=TRUE,col=1,lwd=3)
#curve(0.06*x**(-gamma),add=TRUE,col=1,lwd=3)
legend("bottomleft",legend=c(t1,t4,t3,t2),lty=c(1,-1,-1,-1),lwd=2,col=c(1,1,1,1),pch=c(-1,16,1,20),cex=1.0 )

#omega=1.0###################################################################################################
rm(list=ls())
load("Data/3/1/09/NBD02.rda")
load("Data/3/1/099/NBD02.rda")
load("Data/3/1/0999/NBD02.rda")

gamma_nu0_tau_omega<-function(nu0,tau1,tau2,tau3,n1,n2,n3,omega) 1-2*nu0*(tau1*n1+tau2*n2+tau3*n3)/(omega+1)
gamma <- gamma_nu0_tau_omega(0.2,1,2,3,0.3,0.2,0.5,1) 

t1  <- "exponent=0.56"
t2  <- expression(n=0.9)
t3  <- expression(n=0.99)
t4  <- expression(n=0.999)
plot(hist3$x,hist3$y,log="xy",
     xlab=expression(nu),
     ylab=expression(paste("P"[SS],"(",nu,")")),
     main=expression(paste("(e) ",omega,"=1.0,",nu[0],"=0.2")),
     ylim=c(1e-8,1e0),col=1,pch=16,cex.lab=1.05)
points(hist2$x,hist2$y,col=1,pch=1)
points(hist1$x,hist1$y,col=1,pch=20)
curve(0.04*x**(-gamma),add=TRUE,col=1,lwd=3)
legend("bottomleft",legend=c(t1,t4,t3,t2),lty=c(1,-1,-1,-1),lwd=2,col=c(1,1,1,1),pch=c(-1,16,1,20),cex=1.0 )

#omega=10.0##################################################################################################
rm(list=ls())
load("Data/3/10/09/NBD02.rda")
load("Data/3/10/099/NBD02.rda")
load("Data/3/10/0999/NBD02.rda")

gamma_nu0_tau_omega<-function(nu0,tau1,tau2,tau3,n1,n2,n3,omega) 1-2*nu0*(tau1*n1+tau2*n2+tau3*n3)/(omega+1)
gamma <- gamma_nu0_tau_omega(0.2,1,2,3,0.3,0.2,0.5,10) 

t1  <- "exponent=0.92"
t2  <- expression(n=0.9)
t3  <- expression(n=0.99)
t4  <- expression(n=0.999)
plot(hist3$x,hist3$y,log="xy",
     xlab=expression(nu),
     ylab=expression(paste("P"[SS],"(",nu,")")),
     main=expression(paste("(f) ",omega,"=10.0,",nu[0],"=0.2")),
     ylim=c(1e-8,1e0),col=1,pch=16,cex.lab=1.05)
points(hist2$x,hist2$y,col=1,pch=1)
points(hist1$x,hist1$y,col=1,pch=20)
curve(0.06*x**(-gamma),add=TRUE,col=1,lwd=3)
legend("bottomleft",legend=c(t1,t4,t3,t2),lty=c(1,-1,-1,-1),lwd=2,col=c(1,1,1,1),pch=c(-1,16,1,20),cex=1.0 )
```

### $\nu_0 = 1.0,n=0.9,0.99,0.999$

```{r}
rm(list=ls())
library(data.table)

#omega=0.01#############################################################################################
load("Data/3/001/09/NBD1.rda")
load("Data/3/001/099/NBD1.rda")
load("Data/3/001/0999/NBD1.rda")

gamma_nu0_tau_omega<-function(nu0,tau1,tau2,tau3,n1,n2,n3,omega) 1-2*nu0*(tau1*n1+tau2*n2+tau3*n3)/(omega+1)
gamma <- gamma_nu0_tau_omega(1,1,2,3,0.3,0.2,0.5,0.01) 

t1  <- "exponent=-3.3564"
t2  <- expression(n=0.9)
t3  <- expression(n=0.99)
t4  <- expression(n=0.999)
plot(hist3$x,hist3$y,log="xy",
     xlab=expression(nu),
     ylab=expression(paste("P"[SS],"(",nu,")")),
     main=expression(paste("(g) ",omega,"=0.01,",nu[0],"=1.0")),
     ylim=c(1e-8,1e0),col=1,pch=16,cex.lab=1.05)
points(hist2$x,hist2$y,col=1,pch=1)
points(hist1$x,hist1$y,col=1,pch=20)
curve(0.000000000009*x**(-gamma),add=TRUE,col=1,lwd=3)
curve(0.00000009*x**(-gamma),add=TRUE,col=1,lwd=3)
legend("bottomleft",legend=c(t1,t4,t3,t2),lty=c(1,-1,-1,-1),lwd=2,col=c(1,1,1,1),pch=c(-1,16,1,20),cex=1.0 )

#omega=1.0###################################################################################################
rm(list=ls())
load("Data/3/1/09/NBD1.rda")
load("Data/3/1/099/NBD1.rda")
load("Data/3/1/0999/NBD1.rda")

gamma_nu0_tau_omega<-function(nu0,tau1,tau2,tau3,n1,n2,n3,omega) 1-2*nu0*(tau1*n1+tau2*n2+tau3*n3)/(omega+1)
gamma <- gamma_nu0_tau_omega(1,1,2,3,0.3,0.2,0.5,1) 

t1  <- "exponent=-1.2"
t2  <- expression(n=0.9)
t3  <- expression(n=0.99)
t4  <- expression(n=0.999)
plot(hist3$x,hist3$y,log="xy",
     xlab=expression(nu),
     ylab=expression(paste("P"[SS],"(",nu,")")),
     main=expression(paste("(h) ",omega,"=1.0,",nu[0],"=1.0")),
     ylim=c(1e-8,1e0),col=1,pch=16,cex.lab=1.05)
points(hist2$x,hist2$y,col=1,pch=1)
points(hist1$x,hist1$y,col=1,pch=20)
curve(0.000001*x**(-gamma),add=TRUE,col=1,lwd=3)
curve(0.0002*x**(-gamma),add=TRUE,col=1,lwd=3)
legend("bottomleft",legend=c(t1,t4,t3,t2),lty=c(1,-1,-1,-1),lwd=2,col=c(1,1,1,1),pch=c(-1,16,1,20),cex=1.0 )

#omega=10.0##################################################################################################
rm(list=ls())
load("Data/3/10/09/NBD1.rda")
load("Data/3/10/099/NBD1.rda")
load("Data/3/10/0999/NBD1.rda")

gamma_nu0_tau_omega<-function(nu0,tau1,tau2,tau3,n1,n2,n3,omega) 1-2*nu0*(tau1*n1+tau2*n2+tau3*n3)/(omega+1)
gamma <- gamma_nu0_tau_omega(1,1,2,3,0.3,0.2,0.5,10) 

t1  <- "exponent=0.6"
t2  <- expression(n=0.9)
t3  <- expression(n=0.99)
t4  <- expression(n=0.999)
plot(hist3$x,hist3$y,log="xy",
     xlab=expression(nu),
     ylab=expression(paste("P"[SS],"(",nu,")")),
     main=expression(paste("(i) ",omega,"=10.0,",nu[0],"=1.0")),
     ylim=c(1e-8,1e0),col=1,pch=16,cex.lab=1.05)
points(hist2$x,hist2$y,col=1,pch=1)
points(hist1$x,hist1$y,col=1,pch=20)
curve(0.02*x**(-gamma),add=TRUE,col=1,lwd=3)
legend("bottomleft",legend=c(t1,t4,t3,t2),lty=c(1,-1,-1,-1),lwd=2,col=c(1,1,1,1),pch=c(-1,16,1,20),cex=1.0 )
```

# 2
## $gamma=11$
### $\nu_0 = 0.01,n=0.9,0.99,0.999$

```{r}
rm(list=ls())
library(data.table)

#omega=0.01#############################################################################################
load("Data/ingamma/001/09/NBD001.rda")
load("Data/ingamma/001/099/NBD001.rda")
load("Data/ingamma/001/0999/NBD001.rda")

ingamma_nu0_omega_gamma<-function(nu0,omega,gamma) 1-2*nu0/((omega+1)*(gamma-1))
ingamma <- ingamma_nu0_omega_gamma(0.01,0.01,11.0) 

t1  <- "exponent=0.99802"
t2  <- expression(n=0.9)
t3  <- expression(n=0.99)
t4  <- expression(n=0.999)
plot(hist3$x,hist3$y,log="xy",
     xlab=expression(nu),
     ylab=expression(paste("P"[SS],"(",nu,")")),
     main=expression(paste("(a) ",omega,"=0.01,",nu[0],"=0.01")),
     ylim=c(1e-10,1e0),col=1,pch=16,cex.lab=1.05)
points(hist2$x,hist2$y,col=1,pch=1)
points(hist1$x,hist1$y,col=1,pch=20)
curve(0.003*x**(-ingamma),add=TRUE,col=1,lwd=3)
legend("bottomleft",legend=c(t1,t4,t3,t2),lty=c(1,-1,-1,-1),lwd=2,col=c(1,1,1,1),pch=c(-1,16,1,20),cex=1.0 )

#omega=1.0###################################################################################################
rm(list=ls())
load("Data/ingamma/1/09/NBD001.rda")
load("Data/ingamma/1/099/NBD001.rda")
load("Data/ingamma/1/0999/NBD001.rda")

ingamma_nu0_omega_gamma<-function(nu0,omega,gamma) 1-2*nu0/((omega+1)*(gamma-1))
ingamma <- ingamma_nu0_omega_gamma(0.01,1.0,11.0) 

t1  <- "exponent=0.999"
t2  <- expression(n=0.9)
t3  <- expression(n=0.99)
t4  <- expression(n=0.999)
plot(hist3$x,hist3$y,log="xy",
     xlab=expression(nu),
     ylab=expression(paste("P"[SS],"(",nu,")")),
     main=expression(paste("(b) ",omega,"=1.0,",nu[0],"=0.01")),
     ylim=c(1e-10,1e0),col=1,pch=16,cex.lab=1.05)
points(hist2$x,hist2$y,col=1,pch=1)
points(hist1$x,hist1$y,col=1,pch=20)
curve(0.0015*x**(-ingamma),add=TRUE,col=1,lwd=3)
legend("bottomleft",legend=c(t1,t4,t3,t2),lty=c(1,-1,-1,-1),lwd=2,col=c(1,1,1,1),pch=c(-1,16,1,20),cex=1.0 )

#omega=10.0##################################################################################################
rm(list=ls())
load("Data/ingamma/10/09/NBD001.rda")
load("Data/ingamma/10/099/NBD001.rda")
load("Data/ingamma/10/0999/NBD001.rda")

ingamma_nu0_omega_gamma<-function(nu0,omega,gamma) 1-2*nu0/((omega+1)*(gamma-1))
ingamma <- ingamma_nu0_omega_gamma(0.01,10,11.0) 

t1  <- "exponent=0.99982"
t2  <- expression(n=0.9)
t3  <- expression(n=0.99)
t4  <- expression(n=0.999)
plot(hist3$x,hist3$y,log="xy",
     xlab=expression(nu),
     ylab=expression(paste("P"[SS],"(",nu,")")),
     main=expression(paste("(c) ",omega,"=10.0,",nu[0],"=0.01")),
     ylim=c(1e-11,1e0),col=1,pch=16,cex.lab=1.05)
points(hist2$x,hist2$y,col=1,pch=1)
points(hist1$x,hist1$y,col=1,pch=20)
curve(0.0003*x**(-ingamma),add=TRUE,col=1,lwd=3)
legend("bottomleft",legend=c(t1,t4,t3,t2),lty=c(1,-1,-1,-1),lwd=2,col=c(1,1,1,1),pch=c(-1,16,1,20),cex=1.0 )
```

### $\nu_0 = 0.2,n=0.9,0.99,0.999$

```{r}
rm(list=ls())
library(data.table)

#omega=0.01#############################################################################################
load("Data/ingamma/001/09/NBD02.rda")
load("Data/ingamma/001/099/NBD02.rda")
load("Data/ingamma/001/0999/NBD02.rda")

ingamma_nu0_omega_gamma<-function(nu0,omega,gamma) 1-2*nu0/((omega+1)*(gamma-1))
ingamma <- ingamma_nu0_omega_gamma(0.2,0.01,11.0) 

t1  <- "exponent=0.9604"
t2  <- expression(n=0.9)
t3  <- expression(n=0.99)
t4  <- expression(n=0.999)
plot(hist3$x,hist3$y,log="xy",
     xlab=expression(nu),
     ylab=expression(paste("P"[SS],"(",nu,")")),
     main=expression(paste("(d) ",omega,"=0.01,",nu[0],"=0.2")),
     ylim=c(1e-10,1e0),col=1,pch=16,cex.lab=1.05)
points(hist2$x,hist2$y,col=1,pch=1)
points(hist1$x,hist1$y,col=1,pch=20)
curve(0.03*x**(-ingamma),add=TRUE,col=1,lwd=3)
legend("bottomleft",legend=c(t1,t4,t3,t2),lty=c(1,-1,-1,-1),lwd=2,col=c(1,1,1,1),pch=c(-1,16,1,20),cex=1.0 )

#omega=1.0###################################################################################################
rm(list=ls())
load("Data/ingamma/1/09/NBD02.rda")
load("Data/ingamma/1/099/NBD02.rda")
load("Data/ingamma/1/0999/NBD02.rda")

ingamma_nu0_omega_gamma<-function(nu0,omega,gamma) 1-2*nu0/((omega+1)*(gamma-1))
ingamma <- ingamma_nu0_omega_gamma(0.2,1.0,11.0) 

t1  <- "exponent=0.98"
t2  <- expression(n=0.9)
t3  <- expression(n=0.99)
t4  <- expression(n=0.999)
plot(hist3$x,hist3$y,log="xy",
     xlab=expression(nu),
     ylab=expression(paste("P"[SS],"(",nu,")")),
     main=expression(paste("(e) ",omega,"=1.0,",nu[0],"=0.2")),
     ylim=c(1e-10,1e0),col=1,pch=16,cex.lab=1.05)
points(hist2$x,hist2$y,col=1,pch=1)
points(hist1$x,hist1$y,col=1,pch=20)
curve(0.02*x**(-ingamma),add=TRUE,col=1,lwd=3)
legend("bottomleft",legend=c(t1,t4,t3,t2),lty=c(1,-1,-1,-1),lwd=2,col=c(1,1,1,1),pch=c(-1,16,1,20),cex=1.0 )

#omega=10.0##################################################################################################
rm(list=ls())
load("Data/ingamma/10/09/NBD02.rda")
load("Data/ingamma/10/099/NBD02.rda")
load("Data/ingamma/10/0999/NBD02.rda")

ingamma_nu0_omega_gamma<-function(nu0,omega,gamma) 1-2*nu0/((omega+1)*(gamma-1))
ingamma <- ingamma_nu0_omega_gamma(0.2,10,11.0) 

t1  <- "exponent=0.9964"
t2  <- expression(n=0.9)
t3  <- expression(n=0.99)
t4  <- expression(n=0.999)
plot(hist3$x,hist3$y,log="xy",
     xlab=expression(nu),
     ylab=expression(paste("P"[SS],"(",nu,")")),
     main=expression(paste("(f) ",omega,"=10.0,",nu[0],"=0.2")),
     ylim=c(1e-11,1e0),col=1,pch=16,cex.lab=1.05)
points(hist2$x,hist2$y,col=1,pch=1)
points(hist1$x,hist1$y,col=1,pch=20)
curve(0.004*x**(-ingamma),add=TRUE,col=1,lwd=3)
legend("bottomleft",legend=c(t1,t4,t3,t2),lty=c(1,-1,-1,-1),lwd=2,col=c(1,1,1,1),pch=c(-1,16,1,20),cex=1.0 )
```

### $\nu_0 = 1.0,n=0.9,0.99,0.999$

```{r}
rm(list=ls())
library(data.table)

#omega=0.01#############################################################################################
load("Data/ingamma/001/09/NBD1.rda")
load("Data/ingamma/001/099/NBD1.rda")
load("Data/ingamma/001/0999/NBD1.rda")

ingamma_nu0_omega_gamma<-function(nu0,omega,gamma) 1-2*nu0/((omega+1)*(gamma-1))
ingamma <- ingamma_nu0_omega_gamma(1,0.01,11.0) 

t1  <- "exponent=0.802"
t2  <- expression(n=0.9)
t3  <- expression(n=0.99)
t4  <- expression(n=0.999)
plot(hist3$x,hist3$y,log="xy",
     xlab=expression(nu),
     ylab=expression(paste("P"[SS],"(",nu,")")),
     main=expression(paste("(g) ",omega,"=0.01,",nu[0],"=1.0")),
     ylim=c(1e-10,1e0),col=1,pch=16,cex.lab=1.05)
points(hist2$x,hist2$y,col=1,pch=1)
points(hist1$x,hist1$y,col=1,pch=20)
curve(0.05*x**(-ingamma),add=TRUE,col=1,lwd=3)
legend("bottomleft",legend=c(t1,t4,t3,t2),lty=c(1,-1,-1,-1),lwd=2,col=c(1,1,1,1),pch=c(-1,16,1,20),cex=1.0 )

#omega=1.0###################################################################################################
rm(list=ls())
load("Data/ingamma/1/09/NBD1.rda")
load("Data/ingamma/1/099/NBD1.rda")
load("Data/ingamma/1/0999/NBD1.rda")

ingamma_nu0_omega_gamma<-function(nu0,omega,gamma) 1-2*nu0/((omega+1)*(gamma-1))
ingamma <- ingamma_nu0_omega_gamma(1,1.0,11.0) 

t1  <- "exponent=0.9"
t2  <- expression(n=0.9)
t3  <- expression(n=0.99)
t4  <- expression(n=0.999)
plot(hist3$x,hist3$y,log="xy",
     xlab=expression(nu),
     ylab=expression(paste("P"[SS],"(",nu,")")),
     main=expression(paste("(h) ",omega,"=1.0,",nu[0],"=1.0")),
     ylim=c(1e-10,1e0),col=1,pch=16,cex.lab=1.05)
points(hist2$x,hist2$y,col=1,pch=1)
points(hist1$x,hist1$y,col=1,pch=20)
curve(0.05*x**(-ingamma),add=TRUE,col=1,lwd=3)
legend("bottomleft",legend=c(t1,t4,t3,t2),lty=c(1,-1,-1,-1),lwd=2,col=c(1,1,1,1),pch=c(-1,16,1,20),cex=1.0 )

#omega=10.0##################################################################################################
rm(list=ls())
load("Data/ingamma/10/09/NBD1.rda")
load("Data/ingamma/10/099/NBD1.rda")
load("Data/ingamma/10/0999/NBD1.rda")

ingamma_nu0_omega_gamma<-function(nu0,omega,gamma) 1-2*nu0/((omega+1)*(gamma-1))
ingamma <- ingamma_nu0_omega_gamma(1,10,11.0) 

t1  <- "exponent=0.982"
t2  <- expression(n=0.9)
t3  <- expression(n=0.99)
t4  <- expression(n=0.999)
plot(hist3$x,hist3$y,log="xy",
     xlab=expression(nu),
     ylab=expression(paste("P"[SS],"(",nu,")")),
     main=expression(paste("(i) ",omega,"=10.0,",nu[0],"=1.0")),
     ylim=c(1e-11,1e0),col=1,pch=16,cex.lab=1.05)
points(hist2$x,hist2$y,col=1,pch=1)
points(hist1$x,hist1$y,col=1,pch=20)
curve(0.02*x**(-ingamma),add=TRUE,col=1,lwd=3)
legend("bottomleft",legend=c(t1,t4,t3,t2),lty=c(1,-1,-1,-1),lwd=2,col=c(1,1,1,1),pch=c(-1,16,1,20),cex=1.0 )
```